import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../common/components/layout/Layout';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Salesforce NextAuth Demo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <p>test</p>
            </Layout>
        </>
    );
};

export default Home;
